base:
  random_state: 100
  repo_path: '/data/home/yaantok1/Rec_Sys_S/Jupyter/ml_engineering_example'

load_data:
  folder: datasets
  file: station_data.xlsx

fen: # features_engeneering
  features_to_drop: ['air_temp_mean']

preprocessing:
  preprocess_outliers: ['air_humidity_min']

output:
  features: 'features.csv'
  model: 'model.joblib'
  output_file: 'station_data_predictions.xlsx'

train:
  target_column: 'leaf_humidity_min'
  output_column: 'prediction'
  select: ['air_temp_max', 'air_temp_min', 'dew_point_mean', 'dew_point_min', 'air_humidity_mean', 'air_humidity_max', 'air_humidity_min', 'wind_speed_mean', 'wind_speed_max']
  catboost:
    iterations: 100
    categorical: []